# Site
repository: nimaman.github.io/cv
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Nima Manaf
title: Data Scientist
email: nima.manaf8@gmail.com
# email_title: Email (Email title override)
website: nimaman.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: nima_mnf
github_username:  NimaMan
instagram_username: nima_manaf
linkedin_username: nima-manaf-phd-02174b74
googlescholar_username: citations?user=oE_9bDkAAAAJ&hl=en

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
 gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
#google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/man.jpg
about_content: | # this will include new lines to allow paragraphs
 As a practical problem-solver with a passion for data science, I thrive on using mathematical, statistical, and machine learning models to improve real-world processes. With a keen eye for detail and the ability to see the big picture, I enjoy combining data, computation power, and intuition to build autonomous decision-making systems that drive measurable improvements. Whether working independently or as part of a team, I am committed to using my skills and expertise to deliver results that exceed expectations.
  
content:
  
  - title: Working Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Rabobank
        sub_title: Data Scientist
        caption: May 2022 - Present
        link: 
        quote: >
          I work as a Data Scientist in the Risk Analytics Department in Rabobank
        description: | # this will include new lines to allow paragraphs
          I began my professional journey with Rabobank as a member of the Model Monitoring team, and later transitioned to become a Model Consultant within the Methodology team of the Credit Analytics Department.
          During my tenure, I took on numerous projects that enabled me to gain a holistic understanding of the department's operations and strategic goals. Alongside contributing to the organization's growth through various projects, such as the ECB ML Survey, I also kept a keen eye on the finer details such as implementing state of the most recent ECB Guidelines.
          Some of my projects during this period are:
          - ECB ML Survey: I investigated the usage of ML models within Tribe Credit Analytics to be reported to ECB
          - Point of Contact Model Consultant to address methodological challenges of the Rural Portfolio      
          - Python implementation of the latest EBA Guidelines for Economic Downtrun Detection and Calibration
          - Development of Challenger Models for different teams such as IFRS9
          - Design and implementation of Model Monitoring frameworks for Risk-Adjusted Return on Capital

      - layout: left
        border: weak
        title: Eindhoven University of Technology
        sub_title: Postdoctoral Research Associate
        caption: Sept 2020 - April 2022
        link: 
        quote: >
          I conduct research as a member of the Future Logistics project and supervise students.  
        description: | # this will include new lines to allow paragraphs
          I conduct my postdoctoral research as a member of the [Future Logistics](https://research.tue.nl/en/projects/future-logistics-een-proeftuin-voor-high-tech-service-logistiek) project.
          My research mainly focused on developing block evolutionary training, extending the reinforced genetic algorithm to Travelling Salesman and Maximum Cut problems, 
          and using Reinforcement Learning and Evolutions Strategies for solving inventory management problems. 

          In addition to research, I also supervise Bachelors' and Masters' student theses. 
          You can find a list of Master's student theses that I was involved in either as a [thesis supervisor or assessor here](https://research.tue.nl/en/persons/manafzadeh-dizbin-manafzadeh-dizbin/supervised-student-theses/).

      - layout: left
        border: weak
        title: Bosch Center for AI
        sub_title: PhD Industrial Sabbatical
        caption: Feb 2019 - Jan 2020
        link: 
        quote: >
          I worked on a project using Machine Learning for automating the scheduling decisions in semiconductor wafer fabrication.
        description: | # this will include new lines to allow paragraphs
          I worked on a research project using Q-Learning and Monte-Carlo Tree Search for solving parallel machine scheduling problems that arise in semiconductor wafer fabrication. 
          In addition, I started developing the reinforced genetic algorithm (RGA) for parallel machine scheduling problems. I extended RGA to solve Travelling Salesman and Maximum Cut problems later on. 
          I also analyzed a dataset from Ion Implantation of the semiconductor wafer fabrication of Bosch company and extracted the existing patterns in the data.  
      - layout: left
        title: Koç University 
        sub_title: PhD Candidate in Business Administration
        caption: Sept 2016 - Sept 2020
        link: 
        quote: >
          Ph.D. Thesis Title:  Modelling and Control of Production Systems Based on Observed Inter-event Times: An Analytical and Empirical Investigation
        description: | # this will include new lines to allow paragraphs
          I conducted my research under the supervision of [Prof. Dr. Barış Tan](http://home.ku.edu.tr/~btan/) as part of the **Process Virtualization** and **Process Control** work packages of the 
          [Productive4.0](https://productive40.eu/) project. My contributions can be summarised as follows:
          - I analyzed several hundred million rows of event data from several hundred machines in the semiconductor wafer fabrication of the Bosch Company.
          - I developed machine learning and statistical methods to predict the production times of the products in the production network.
          - I conducted theoretical research on the implications of the data-analysis results on the optimal control of the system.
          
          For further detail, you can refer to my Ph.D. Thesis and my publications.  

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Machine Learning  
        description: | # this will include new lines to allow paragraphs
          Reinforcement Learning, Supervised Learning, Unsupervised Learning, Deep Learning, Graph Neural Networks, Gradient-Free Learning, Statistical Learning 
      - layout: left
        title: Optimization methods
        description: | # this will include new lines to allow paragraphs
          Combinatorial Optimization, Stochastic Optimization, Evolution Strategies, Genetic Algorithms, Monte-Carlo Tree Search, Markov Decision Processes, Mathematical Programming, Constraint Programming, and Dynamic Programming
      - layout: left
        title: Applications  
        description: | # this will include new lines to allow paragraphs
          Supply Chain Management, Resource Allocation, Inventory Control, Production Planning, Scheduling, Routing, Healthcare Operations, Queuing Systems, Semiconductor Wafer Fabrication
      - layout: left
        title: Software  
        description: | # this will include new lines to allow paragraphs
          - Programming Languages: Python, C++, SQL
          - Python-C++ Integration Module: Pybind11
          -	Parallel Processing Modules: Ray, MPI, Multiprocessing 
          -	Discrete Optimization Modules: Gurobi, CPLEX, LocalSolver, SCIP, Google OR Tools
          -	Machine Learning Modules: Pytorch, Deep Graph Library, Scikit-learn, XGBoost, LightGBM, CatBoost, Statsmodels
          -	Data Analytics and Visualization Modules: Numpy, Scipy, Pandas, cudf, Zarr, Matplotlib, Seaborn, Bokeh, Plotly
          - Versioning tools: git

      - layout: left
        title: Leadership and Coordination  
        description: | # this will include new lines to allow paragraphs
          - Master's Student Thesis Supervision 
          -	Bachelor's Student Thesis Supervision
          - Academia (Research) - Industry (Practice) Project Coordination
            - Productive4.0 Project (coordination between Koç University and Bosch Semiconductor Manufacturing)
            - Autonomous Planing Project (coordination between Bosch Center for Artificial Intelligence and Bosch Semiconductor Manufacturing) 

  - title: Intellectual Properties
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Learn Offline, Search Online, A Hybrid Approach to Solving Scheduling Problems](https://patents.justia.com/patent/20210312280) (Patent No. 389829)
      - Reinforced Random Key Genetic Algorithm for Combinatorial Optimization (under processing)
  
  - title: Grants
    layout: text
    content: | # this will include new lines to allow paragraphs
      - NWO (The Dutch Research Council) 500,000 Computing Time Grant on National Computer Facilities

  - title: Honors and Rewards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Academic Excellence Award - Koç University, Sept 2020
      - Research Scholarship - The Scientific and Technological Research Council of Turkey, Sept 2018 - Feb 2019
      - Research Scholarship - Koç University, Sept 2014 - Sept 2018
      - Bachelor's Scholarship - Sharif University of Technology, Sept 2010 - Aug 2014
      -	Exceptional Talent Student Title (ranked among top 0.1% students in the National University Entrance Exam among more than half a million participants), June 2010
      -	Ranked among the top 1% of the participants in the National Chemistry Olympiad - Iran, Feb 2009

  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs
      -  MSc in Business Theory at  [Koç University](https://en.wikipedia.org/wiki/Ko%C3%A7_University) (Sept 2014 - Sept 2016)

           
      - BSc in Industrial Engineering at [Sharif University of Technology](https://en.wikipedia.org/wiki/Sharif_University_of_Technology) (Sept 2010 - Sept 2014)
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Manafzadeh Dizbin N, Richter, F., and Falkner, S. "Reinforced Genetic Algorithm for Solving Combinatorial Optimization Problems", Working Paper, 2021
      - Manafzadeh Dizbin N., and Tan, B., "Total Cycle Time Prediction of the Products in Semiconductor Wafer Fabrication", Working Paper, 2020
      -  Manafzadeh Dizbin N., Laipple, G., and Tan, B., "Empirical Analysis of Product Flows at a Semiconductor Production System", Working Paper, 2020
      - Manafzadeh Dizbin N. and Tan, B., ["Optimal control of production-inventory systems with correlated demand inter-arrival and processing times"](https://www.sciencedirect.com/science/article/pii/S0925527320300839) 
      in International Journal of Production Economics, 2020
      - Manafzadeh Dizbin N. and Tan, B., ["Modelling and analysis of the impact of correlated inter-event data on production control using Markovian arrival processes"](https://link.springer.com/article/10.1007/s10696-018-9329-7) 
      in Journal of Flexible Service and Manufacturing, 2019
      - Manafzadeh Dizbin N. and Tan, B., "Production Inventory Control with Correlated Demand"
      in The Eleventh International Conference on Stochastic Models of Manufacturing and Service Operations, Italy, 2017
  
  - title: Preview of some of my PhD and Postdoc projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Block Evolutionary Training
        link: https://scholar.google.com/citations?user=r7FWJEkAAAAJ&hl=de
        link_text: In collabration with Stefan Falkner
        additional_links:
          - title: 
            icon: 
            url:
        quote: >
          Our algorithm, Block Evolutionary Training (BET), achieves higher rewards than Reinforcement Learning methods on PyBullet physics engine simulator with significantly smaller neural networks.    
        description: | # this will include new lines to allow paragraphs
          Evolutionary methods are a competitive alternative to DRL methods in solving sequential decision-making problems.
          [Salimans, et al. (2017)](https://arxiv.org/abs/1703.03864) show that a simple variant of the Natural Evolution Strategies can achieve similar performance
          to the Deep Reinforcement Learning methods on Atari and Mujoco environments. We demonstrate that by integrating the structure of the neural policy network into Evolution Strategies 
          one can achieve higher rewards on continuous control tasks such as PyBullet environment. 
      - layout: left
        border: weak
        title: Inventory Management with Evolution Strategies
        link: https://nimaman.github.io/posts/lost_sales_rl/
        link_text: Blog post on Evolution Strategies for solving Lost Sales Inventory Management problem
        additional_links:
          - title:  https://github.com/NimaMan/invman_public
            icon: fab fa-github
            url: Github repository of the project
        quote: >
          We show that Evolution Strategies can learn neural policy networks for managing inventory in different inventory management problems.  
        description: | # this will include new lines to allow paragraphs
          Recently it has been shown that Reinforcement Learning (RL) agents can learn to manage inventory in inventory management problems.
          However, RL methods require [significant hyper-parameter optimization](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3302881). 
          We show that Evolution Strategies can learn neural policy networks for managing inventory in different inventory management problems 
          with an order of magnitude smaller neural networks and without the need for hyper-parameter optimization.   
      - layout: left
        title: Reinforced Genetic Algorithm
        link: 
        link_text: 
        quote: >
          We integrate learning into the genetic algorithm for solving Combinatorial optimization problems using Reinforcement Learning and Evolution Strategies.
        description: | # this will include new lines to allow paragraphs
          We integrate the problem structure of the Combinatorial Optimization problems into Graph Neural Networks (GNN). 
          We demonstrate that a single forward pass of the GNN generates near-optimal solutions to the Parallel Machine Scheduling and maximum cut problems. 
          Then, we train GNNs that act as the mutation operator of the genetic algorithms.
          Our main objective is to learn about the optimization space on small problem instances and use the learned models in solving bigger problem instances.
          This approach helps solve problems where exact methods and heuristics cannot produce acceptable solutions in a reasonable amount of time.  

  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      English (Fluent), Azerbaijani (Native), Turkish (Native), Persian (Native), German (Beginner)
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Hobbies: Reading, Cycling, Swimming, Hiking, Cooking
      
      Interests: Markets, Geopolitics, Evolution       
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
