# Site
repository: nimaman.github.io/cv
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Nima Manafzadeh Dizbin
title: Postdoctoral Research Associate
email: nima.manaf8@gmail.com
# email_title: Email (Email title override)
website: nimaman.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: nima_mnf
github_username:  NimaMan
instagram_username: nima_manaf
linkedin_username: nima-manafzadeh-dizbin-02174b74
googlescholar_username: citations?user=oE_9bDkAAAAJ&hl=en

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/ben2_3.png
about_content: | # this will include new lines to allow paragraphs
  I am detail-oriented person with the ability to look into the bigger picture of the problems that I am tackling.
  My passion is to take the mathematical, statistical, and machine learning models, combine it with data, computation power, and intuition, and deploy it in improving the practical
  processes with the aim of building autonomous decisions making systems.

  My work focuses on two different threds. First, developing intelligent data-driven decision making algorithms for solving optimization problems. 
  Second, using optimization, statistics, and machine learning in solving challenging real-world problems. 

content:
  - title: Recent Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Block Evolutionary Training
        link:
        link_text: 
        additional_links:
          - title: In collabration with [Stefan Falkner](https://scholar.google.com/citations?user=r7FWJEkAAAAJ&hl=de)
            icon: 
            url:
        quote: >
          Our algorithm, Block Evolutionary Training (BET), reaches higher rewards than Reinforcement Learning methods on PyBullet physics engine simulater.    
        description: | # this will include new lines to allow paragraphs
          Evolutionary methods have been shown to be a competitive alternative to DRL methods in solving sequential decision-making problems.
          [Salimans, et al. (2017)](https://arxiv.org/abs/1703.03864) show that a simple variant of the Natural Evolution Strategies can achieve similar performance
          to the Deep Reinforcement Learning methods on Atari and Mujoco environments. We show that by integrating the structure of the neural policy network into Evolution Strategies 
          one can achive higher rewards on continuous control tasks such as PyBullet environment. 
      - layout: left
        border: weak
        title: Inventory Management with Evolution Strategies
        link: https://nimaman.github.io/posts/lost_sales_rl/
        link_text: Blog post on Evolution Strategies for solving Lost Sales Inventory Management problem
        additional_links:
          - title:  https://github.com/NimaMan/invman_public
            icon: fab fa-github
            url: Github repository of the project
        quote: >
          We show that Evolution Strategies can learn neural policy networks for managing inventory in different inventory management problems.  
        description: | # this will include new lines to allow paragraphs
          Recently it has been shown that Reinforcement Learning (RL) agents can learn to manage inventory in inventory management problems.
          However, RL methods require [significant hyper-parameter optimization](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3302881). 
          We show that Evolution Strategies can learn neural policy networks for managing inventory in different inventory management problems 
          with an order of magnitude smaller neural networks and without need for hyper-parameter optimization.   
      - layout: left
        title: Reinforced Genetic Algorithm
        link: 
        link_text: 
        quote: >
          We integrate learning into genetic algorithm for solving Combinatorial Optmization problems using Reinforcement Learning and Evolution Strategies.
        description: | # this will include new lines to allow paragraphs
          Our goals in this project are twofold. First, we train graph neural networks (GNN) that generate near optimal solutions to the Parallel Machine Scheduling, Travelling Salesman, and maximum cut problems
          with a single forward pass of the neural network. Second, we learn GNNs that act as the mutation operator of the genetic algorithms. Our main objective is to train GNNs on smaller problems and transfer the results 
          for solving bigger problems. This is particularly useful for problems where exact methods are computationally intensive and heuristics cannot produce acceptable solutions.  

  - title: Working Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Eindhoven University of Technology
        sub_title: Postdoctoral Research Associate
        caption: Sept 2020 - present
        link: 
        quote: >
          I conduct research as a member of the Future Logistics project and supervise students.  
        description: | # this will include new lines to allow paragraphs
          I conducted my postdoctoral research as a member of the [Future Logistics](https://research.tue.nl/en/projects/future-logistics-een-proeftuin-voor-high-tech-service-logistiek) project.
          My research mainly focused on developing block evolutionary training, extending reinforced genetic algorithm to Travelling Salesman and Maximum Cut problems, 
          and using Reinforcement Learning and Evolutions Strategies for solving inventory management problems. 

          In addition to research, I was also involved in supervising Bachelor's and Master's student thesis. 
          You can find a list of Master's student theses that I was involved in either as a [thesis supervisor or assessor here](https://research.tue.nl/en/persons/manafzadeh-dizbin-manafzadeh-dizbin/supervised-student-theses/).

      - layout: left
        border: weak
        title: Bosch Center for AI
        sub_title: PhD Industrial Sabbatical
        caption: Feb 2019 - Jan 2020
        link: 
        quote: >
          I worked on a project using Machine Learning for automating the scheduling decisions in the semiconductor wafer fabrication.
        description: | # this will include new lines to allow paragraphs
          I worked on applying Q-Learning and Monte-Carlo Tree Search to parallel machine scheduling problems arising in semiconductor wafer fabrication. 
          In addition, I started developing the reinforced genetic algorithm for parallel machine scheduling problem which I later extended to Travelling Salesman and Maximum Cut problems. I also analyzed a dataset from Ion Implantation of the semiconductor wafer fabrication of Bosch company, and extracted the existing patterns in the data.  
      - layout: left
        title: Koç University 
        sub_title: PhD Candidate in Business Administration
        caption: Sept 2016 - Sept 2020
        link: 
        quote: >
          PhD Thesis Title:  Modelling and Control of Production Systems Based on Observed Inter-event Times: An Analytical and Empirical Investigation
        description: | # this will include new lines to allow paragraphs
          I conducted my research under supervision of [Prof. Dr. Barış Tan](http://home.ku.edu.tr/~btan/) as part of the **Process Virtualization** and **Process Control** work-packages of the 
          [Productive4.0](https://productive40.eu/) project. My contributions can be summerised as follows:
          - I analysed several hundred million rows of event data from several hundred machines in the semiconductor wafer fabrication of the Bosch Company.
          - I developed machine learning and statistical methods to predict the production times of the products in the production network.
          - I conducted theoretical research on the implications of the data-analysis results on the optimal control of the system.
          
          For further detail you can refer to my PhD Thesis and my publications.  

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Machine Learning  
        description: | # this will include new lines to allow paragraphs
          Reinforcement Learning, Supervised Learning, Unsupervised Learning, Deep Learning, Graph Neural Networks, Gradient-Free Learning, Statistical Learning 
      - layout: left
        title: Optimization methods
        description: | # this will include new lines to allow paragraphs
          Combinatorial Optimization, Stochastic Optimization, Evolution Strategies, Genetic Algorithms, Monte-Carlo Tree Search, Markov Decision Processes, Mathematical Programming, Constraint Programming, and Dynamic Programming
      - layout: left
        title: Applications  
        description: | # this will include new lines to allow paragraphs
          Supply Chain Management, Resource Allocation, Inventory Control, Production Planning, Scheduling, Routing, Healthcare Operations, Queuing Systems, Semiconductor Wafer Fabrication
      - layout: left
        title: Software  
        description: | # this will include new lines to allow paragraphs
          - Programming Languages: Python, C++
          - Python-C++ Integration Module: Pybind11
          -	Parallel Processing Modules: Ray, MPI, Multiprocessing 
          -	Discrete Optimization Modules: Gurobi, CPLEX, LocalSolver, SCIP, Google OR Tools
          -	Deep Learning Modules: Pytorch, Deep Graph Library
          -	Data Analytics and Visualization Modules: Numpy, Pandas, Scipy, Scikit-learn, Matplotlib, Seaborn, Bokeh, Plotly
      - layout: left
        title: Leadership and Coordination  
        description: | # this will include new lines to allow paragraphs
          - Master's Student Thesis Supervision 
          -	Bachelor's Student Thesis Supervision
          - Academia (Research) - Industry (Practice) Project Coordination
            - Productive4.0 Project (coordination between Koç University and Bosch Semiconductor Manufacturing)
            - Autonomous Planing Project (coordination between Bosch Center for Artificial Intelligence and Bosch Semiconductor Manufacturing) 

  - title: Intellectual Properties
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Learn Offline, Search Online, A Hybrid Approach to Solving Scheduling Problems](https://patents.justia.com/patent/20210312280) (Patent No. 389829)
      - Reinforced Random Key Genetic Algorithm for Combinatorial Optimization (under processing)

  - title: Honors and Rewards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Academic Excellence Award - Koç University, Sept 2020
      - Research Scholarship - The Scientific and Technological Research Council of Turkey, Sept 2018 - Feb 2019
      - Research Scholarship - Koç University, Sept 2014 - Sept 2018
      - Bachelor's Scholarship - Sharif University of Technology, Sept 2010 - Aug 2014
      -	Exceptional Talent Student Title (ranked among top 0.1% students in the National University Entrance Exam among more than half a million participants), June 2010
      -	Ranked among the top 1% of the participants in the National Chemistry Olympiad - Iran, Feb 2009

  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs
      -  MSc in Business Theory at  Koç University (Sept 2010 - Sept 2014)

          link to thesis + info about scholarship
      - BSc in Industrial Engineering at [Sharif University of Technology](https://en.wikipedia.org/wiki/Sharif_University_of_Technology) (Sept 2010 - Sept 2014)
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Optimal control of production-inventory systems with correlated demand inter-arrival and processing times](https://www.sciencedirect.com/science/article/pii/S0925527320300839)
      - [Modelling and analysis of the impact of correlated inter-event data on production control using Markovian arrival processes](https://link.springer.com/article/10.1007/s10696-018-9329-7)
  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      English (Fluent), Azerbaijani (Native), Turkish (Native), Persian (Native), German (Beginner)
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
