# Site
repository: nimaman.github.io/cv
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Nima Manaf
title: Data Scientist
email: nima.manaf8@gmail.com
# email_title: Email (Email title override)
website: nimaman.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: nima_manaf
github_username:  NimaMan
instagram_username: nima_manaf
linkedin_username: nima-manaf-phd-02174b74
googlescholar_username: citations?user=oE_9bDkAAAAJ&hl=en

# Additional icon links
#additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
#google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/man.jpg
about_content: | # this will include new lines to allow paragraphs
 I started with a Ph.D. in Business to understand big-picture challenges. But I saw that to make real change, I needed deeper tech skills. So, I dived into engineering, software, and AI. Now, as a data scientist, I use both my broad view and detailed know-how to find smart solutions. I'm always pushing to do better, whether on my own or with a team.  
content:
  
  - title: Working Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Rabobank
        sub_title: Data Scientist
        caption: May 2022 - Present
        link: 
        quote: >
          Driving data analytics at Rabobank's Risk Department
        description: | # this will include new lines to allow paragraphs
          - Spearheaded the EU AI-Act task force.
          - Evaluated ML models for ECB reporting.
          - Addressed methodological challenges for the Rural Portfolio.
          - Adapted latest EBA Guidelines with Python.
          - Developed monitoring frameworks for Risk-Adjusted Return on Capital.
          - Designed and implemented Challenger Models for the IFRS9 team.

      - layout: left
        border: weak
        title: Eindhoven University of Technology
        sub_title: Postdoctoral Research Associate
        caption: Sept 2020 - April 2022
        link: 
        quote: >
          Leading cutting-edge research in the Future Logistics initiative while mentoring the next generation
        description: | # this will include new lines to allow paragraphs
          - Conducted research on evolutionary training of deep neural netrowks as a member of the [Future Logistics](https://research.tue.nl/en/projects/future-logistics-een-proeftuin-voor-high-tech-service-logistiek) project.
          - Applied Reinforcement Learning and Evolution Strategies for inventory management problems.
          - Supervised Bachelor's and Master's student [theses](https://research.tue.nl/en/persons/manafzadeh-dizbin-manafzadeh-dizbin/supervised-student-theses/).  
          
      - layout: left
        border: weak
        title: Bosch Center for AI
        sub_title: PhD Industrial Sabbatical
        caption: Feb 2019 - Jan 2020
        link: 
        quote: >
          Pioneered ML-driven automation for semiconductor decision-making.
        description: | # this will include new lines to allow paragraphs
          - Researched application of Q-Learning and Monte-Carlo Tree Search for parallel machine scheduling problems.
          - Developed the reinforced genetic algorithm.
          - Analyzed large manufacturing network data from the semiconductor wafer fabrication.

      - layout: left
        title: Koç University 
        sub_title: PhD Candidate in Business Administration
        caption: Sept 2016 - Sept 2020
        link: 
        quote: >
          Ph.D. Thesis Title:  Modelling and Control of Production Systems Based on Observed Inter-event Times: An Analytical and Empirical Investigation
        description: | # this will include new lines to allow paragraphs
          I conducted my research under the supervision of [Prof. Dr. Barış Tan](http://home.ku.edu.tr/~btan/) as part of the **Process Virtualization** and **Process Control** work packages of the 
          [Productive4.0](https://productive40.eu/) project. During my Ph.D. I:
          - Analyzed extensive event data from semiconductor wafer fabrication.
          - Developed ML and statistical methods for production time prediction.
          - Conducted theoretical research on optimal control based on data-analysis results.

          For further detail, you can refer to my [Ph.D. Thesis published on Arxiv](https://arxiv.org/abs/2204.01079) or a [short overview of it](https://nimaman.github.io/posts/phd_thesis/) and my publications.  

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Machine Learning and AI
        description: | # this will include new lines to allow paragraphs
          Reinforcement Learning, Supervised Learning, Unsupervised Learning, Deep Learning, Graph Neural Networks, Gradient-Free Learning, Statistical Learning 
      - layout: left
        title: Optimization methods
        description: | # this will include new lines to allow paragraphs
          Combinatorial Optimization, Stochastic Optimization, Evolution Strategies, Genetic Algorithms, Monte-Carlo Tree Search, Markov Decision Processes, Mathematical Programming, Constraint Programming, and Dynamic Programming
      - layout: left
        title: Applications  
        description: | # this will include new lines to allow paragraphs
          Supply Chain Management, Resource Allocation, Inventory Control, Production Planning, Scheduling, Routing, Healthcare Operations, Queuing Systems, Semiconductor Wafer Fabrication
      - layout: left
        title: Software and Programming Languages
        description: | # this will include new lines to allow paragraphs
          - Programming Languages: Python, C++, SQL
          - Python-C++ Integration Module: Pybind11
          -	Parallel Processing Modules: Ray, MPI, Multiprocessing 
          -	Discrete Optimization Modules: Gurobi, CPLEX, LocalSolver, SCIP, Google OR Tools
          -	Machine Learning Modules: Pytorch, Deep Graph Library, Scikit-learn, XGBoost, LightGBM, CatBoost, Statsmodels
          -	Data Analytics and Visualization Modules: Numpy, Scipy, Pandas, cudf, Zarr, Matplotlib, Seaborn, Bokeh, Plotly
          - Versioning tools: git

      - layout: left
        title: Leadership and Coordination  
        description: | # this will include new lines to allow paragraphs
          - Master's Student Thesis Supervision 
          -	Bachelor's Student Thesis Supervision
          - Academia (Research) - Industry (Practice) Project Coordination
          -	Project Management

  - title: Certificates
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Supervising [Bachelor's Student](https://www.linkedin.com/in/nima-manaf-phd-02174b74/overlay/experience/1676821846/multiple-media-viewer/?profileId=ACoAAA_FolkBxdEzai2ebXIchHGXCCzKFwCCJRs&treasuryMediaId=1635523854237)
      - Supervising [Master's Student](https://www.linkedin.com/in/nima-manaf-phd-02174b74/overlay/experience/1676821846/multiple-media-viewer/?profileId=ACoAAA_FolkBxdEzai2ebXIchHGXCCzKFwCCJRs&treasuryMediaId=1635523852219)

  - title: Intellectual Properties
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [Learn Offline, Search Online, A Hybrid Approach to Solving Scheduling Problems](https://patents.justia.com/patent/20210312280) (Patent No. 389829)
      - Reinforced Random Key Genetic Algorithm for Combinatorial Optimization (under processing)
  
  - title: Grants
    layout: text
    content: | # this will include new lines to allow paragraphs
      - NWO (The Dutch Research Council) 500,000 Computing Time Grant on National Computer Facilities
      - NWO (The Dutch Research Council) 1000,000 Computing Time Grant on National Computer Facilities


  - title: Honors and Rewards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Academic Excellence Award - Koç University, Sept 2020
      - Research Scholarship - The Scientific and Technological Research Council of Turkey, Sept 2018 - Feb 2019
      - Research Scholarship - Koç University, Sept 2014 - Sept 2018
      - Bachelor's Scholarship - Sharif University of Technology, Sept 2010 - Aug 2014
      -	Exceptional Talent Student Title (ranked among top 0.1% students in the National University Entrance Exam among more than half a million participants), June 2010
      -	Ranked among the top 1% of the participants in the National Chemistry Olympiad - Iran, Feb 2009

  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs
      -  MSc in Business Theory at  [Koç University](https://en.wikipedia.org/wiki/Ko%C3%A7_University) (Sept 2014 - Sept 2016)

           
      - BSc in Industrial Engineering at [Sharif University of Technology](https://en.wikipedia.org/wiki/Sharif_University_of_Technology) (Sept 2010 - Sept 2014)
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Manafzadeh Dizbin N, Richter, F., and Falkner, S. "Reinforced Genetic Algorithm for Solving Combinatorial Optimization Problems", Working Paper, 2021
      - Manafzadeh Dizbin N., and Tan, B., "Total Cycle Time Prediction of the Products in Semiconductor Wafer Fabrication", Working Paper, 2020
      -  Manafzadeh Dizbin N., Laipple, G., and Tan, B., "Empirical Analysis of Product Flows at a Semiconductor Production System", Working Paper, 2020
      - Manafzadeh Dizbin N. and Tan, B., ["Optimal control of production-inventory systems with correlated demand inter-arrival and processing times"](https://www.sciencedirect.com/science/article/pii/S0925527320300839) 
      in International Journal of Production Economics, 2020
      - Manafzadeh Dizbin N. and Tan, B., ["Modelling and analysis of the impact of correlated inter-event data on production control using Markovian arrival processes"](https://link.springer.com/article/10.1007/s10696-018-9329-7) 
      in Journal of Flexible Service and Manufacturing, 2019
      - Manafzadeh Dizbin N. and Tan, B., "Production Inventory Control with Correlated Demand"
      in The Eleventh International Conference on Stochastic Models of Manufacturing and Service Operations, Italy, 2017
  
  - title: Preview of some of my PhD and Postdoc projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Block Evolutionary Training
        link: https://scholar.google.com/citations?user=r7FWJEkAAAAJ&hl=de
        link_text: In collabration with Stefan Falkner
        additional_links:
          - title: 
            icon: 
            url:
        quote: >
          Our algorithm, Block Evolutionary Training (BET), achieves higher rewards than Reinforcement Learning methods on PyBullet physics engine simulator with significantly smaller neural networks.    
        description: | # this will include new lines to allow paragraphs
          Evolutionary methods are a competitive alternative to DRL methods in solving sequential decision-making problems.
          [Salimans, et al. (2017)](https://arxiv.org/abs/1703.03864) show that a simple variant of the Natural Evolution Strategies can achieve similar performance
          to the Deep Reinforcement Learning methods on Atari and Mujoco environments. We demonstrate that by integrating the structure of the neural policy network into Evolution Strategies 
          one can achieve higher rewards on continuous control tasks such as PyBullet environment. 
      - layout: left
        border: weak
        title: Inventory Management with Evolution Strategies
        link: https://nimaman.github.io/posts/lost_sales_rl/
        link_text: Blog post on Evolution Strategies for solving Lost Sales Inventory Management problem
        additional_links:
          - title:  https://github.com/NimaMan/invman_public
            icon: fab fa-github
            url: Github repository of the project
        quote: >
          We show that Evolution Strategies can learn neural policy networks for managing inventory in different inventory management problems.  
        description: | # this will include new lines to allow paragraphs
          Recently it has been shown that Reinforcement Learning (RL) agents can learn to manage inventory in inventory management problems.
          However, RL methods require [significant hyper-parameter optimization](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3302881). 
          We show that Evolution Strategies can learn neural policy networks for managing inventory in different inventory management problems 
          with an order of magnitude smaller neural networks and without the need for hyper-parameter optimization.   
      - layout: left
        title: Reinforced Genetic Algorithm
        link: 
        link_text: 
        quote: >
          We integrate learning into the genetic algorithm for solving Combinatorial optimization problems using Reinforcement Learning and Evolution Strategies.
        description: | # this will include new lines to allow paragraphs
          We integrate the problem structure of the Combinatorial Optimization problems into Graph Neural Networks (GNN). 
          We demonstrate that a single forward pass of the GNN generates near-optimal solutions to the Parallel Machine Scheduling and maximum cut problems. 
          Then, we train GNNs that act as the mutation operator of the genetic algorithms.
          Our main objective is to learn about the optimization space on small problem instances and use the learned models in solving bigger problem instances.
          This approach helps solve problems where exact methods and heuristics cannot produce acceptable solutions in a reasonable amount of time.  

  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      English (Fluent), Azerbaijani (Native), Turkish (Native), Persian (Native), German (Beginner)
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Hobbies: Reading, Cycling, Swimming, Hiking, Cooking
      
      Interests: Markets, Geopolitics, Evolution       
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
