name: CI workflow

on:
  push:
    branches: [ master ]  # Change to your main branch name if it's not 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Make sure this matches your Python version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Freeze Flask app
      run: |
        source venv/bin/activate
        python freeze.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # This should be the directory where Frozen-Flask generates the static files
